// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanlyDiemAPI.Data;

#nullable disable

namespace QuanlyDiemAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("QuanlyDiemAPI.Models.DangKyMonHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MonHocId")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("SinhVienId")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("MonHocId");

                    b.HasIndex("SinhVienId", "MonHocId")
                        .IsUnique();

                    b.ToTable("DangKyMonHocs");
                });

            modelBuilder.Entity("QuanlyDiemAPI.Models.DanhgiaAI", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AiComment")
                        .HasColumnType("longtext");

                    b.Property<float>("Gpa")
                        .HasColumnType("float");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.ToTable("DanhgiaAIs");
                });

            modelBuilder.Entity("QuanlyDiemAPI.Models.Diem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<float?>("CC")
                        .HasColumnType("float");

                    b.Property<float?>("Exam")
                        .HasColumnType("float");

                    b.Property<int?>("GiangVienId")
                        .HasColumnType("int");

                    b.Property<float?>("KT1")
                        .HasColumnType("float");

                    b.Property<float?>("KT2")
                        .HasColumnType("float");

                    b.Property<float?>("KT3")
                        .HasColumnType("float");

                    b.Property<int>("MonHocId")
                        .HasColumnType("int");

                    b.Property<int>("SinhVienId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GiangVienId");

                    b.HasIndex("MonHocId");

                    b.HasIndex("SinhVienId", "MonHocId")
                        .IsUnique();

                    b.ToTable("Diems");
                });

            modelBuilder.Entity("QuanlyDiemAPI.Models.GiangVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Department")
                        .HasColumnType("longtext");

                    b.Property<DateOnly?>("Dob")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Gender")
                        .HasColumnType("longtext");

                    b.Property<int?>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("NguoiDungId")
                        .IsUnique();

                    b.ToTable("GiangViens");
                });

            modelBuilder.Entity("QuanlyDiemAPI.Models.LopHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AdvisorId")
                        .HasColumnType("int");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Department")
                        .HasColumnType("longtext");

                    b.Property<string>("Room")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AdvisorId");

                    b.ToTable("LopHocs");
                });

            modelBuilder.Entity("QuanlyDiemAPI.Models.MonHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Credits")
                        .HasColumnType("int");

                    b.Property<string>("Department")
                        .HasColumnType("longtext");

                    b.Property<int?>("GiangVienId")
                        .HasColumnType("int");

                    b.Property<int>("HocKy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("GiangVienId");

                    b.ToTable("MonHocs");
                });

            modelBuilder.Entity("QuanlyDiemAPI.Models.NguoiDung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MatKhauGoc")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("NguoiDungs");
                });

            modelBuilder.Entity("QuanlyDiemAPI.Models.SinhVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Class")
                        .HasColumnType("longtext");

                    b.Property<string>("Course")
                        .HasColumnType("longtext");

                    b.Property<string>("Department")
                        .HasColumnType("longtext");

                    b.Property<DateOnly?>("Dob")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Gender")
                        .HasColumnType("longtext");

                    b.Property<int?>("LopHocId")
                        .HasColumnType("int");

                    b.Property<int?>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("LopHocId");

                    b.HasIndex("NguoiDungId")
                        .IsUnique();

                    b.ToTable("SinhViens");
                });

            modelBuilder.Entity("QuanlyDiemAPI.Models.DangKyMonHoc", b =>
                {
                    b.HasOne("QuanlyDiemAPI.Models.MonHoc", "MonHoc")
                        .WithMany()
                        .HasForeignKey("MonHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanlyDiemAPI.Models.SinhVien", "SinhVien")
                        .WithMany()
                        .HasForeignKey("SinhVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MonHoc");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("QuanlyDiemAPI.Models.DanhgiaAI", b =>
                {
                    b.HasOne("QuanlyDiemAPI.Models.SinhVien", "SinhVien")
                        .WithOne("DanhgiaAI")
                        .HasForeignKey("QuanlyDiemAPI.Models.DanhgiaAI", "StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("QuanlyDiemAPI.Models.Diem", b =>
                {
                    b.HasOne("QuanlyDiemAPI.Models.GiangVien", "GiangVien")
                        .WithMany()
                        .HasForeignKey("GiangVienId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QuanlyDiemAPI.Models.MonHoc", "MonHoc")
                        .WithMany("Diems")
                        .HasForeignKey("MonHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanlyDiemAPI.Models.SinhVien", "SinhVien")
                        .WithMany("Diems")
                        .HasForeignKey("SinhVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GiangVien");

                    b.Navigation("MonHoc");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("QuanlyDiemAPI.Models.GiangVien", b =>
                {
                    b.HasOne("QuanlyDiemAPI.Models.NguoiDung", "NguoiDung")
                        .WithOne("GiangVien")
                        .HasForeignKey("QuanlyDiemAPI.Models.GiangVien", "NguoiDungId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("QuanlyDiemAPI.Models.LopHoc", b =>
                {
                    b.HasOne("QuanlyDiemAPI.Models.GiangVien", "Advisor")
                        .WithMany("LopHocs")
                        .HasForeignKey("AdvisorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Advisor");
                });

            modelBuilder.Entity("QuanlyDiemAPI.Models.MonHoc", b =>
                {
                    b.HasOne("QuanlyDiemAPI.Models.GiangVien", "GiangVien")
                        .WithMany("MonHocs")
                        .HasForeignKey("GiangVienId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("GiangVien");
                });

            modelBuilder.Entity("QuanlyDiemAPI.Models.SinhVien", b =>
                {
                    b.HasOne("QuanlyDiemAPI.Models.LopHoc", "LopHoc")
                        .WithMany("SinhViens")
                        .HasForeignKey("LopHocId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QuanlyDiemAPI.Models.NguoiDung", "NguoiDung")
                        .WithOne("SinhVien")
                        .HasForeignKey("QuanlyDiemAPI.Models.SinhVien", "NguoiDungId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("LopHoc");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("QuanlyDiemAPI.Models.GiangVien", b =>
                {
                    b.Navigation("LopHocs");

                    b.Navigation("MonHocs");
                });

            modelBuilder.Entity("QuanlyDiemAPI.Models.LopHoc", b =>
                {
                    b.Navigation("SinhViens");
                });

            modelBuilder.Entity("QuanlyDiemAPI.Models.MonHoc", b =>
                {
                    b.Navigation("Diems");
                });

            modelBuilder.Entity("QuanlyDiemAPI.Models.NguoiDung", b =>
                {
                    b.Navigation("GiangVien");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("QuanlyDiemAPI.Models.SinhVien", b =>
                {
                    b.Navigation("DanhgiaAI");

                    b.Navigation("Diems");
                });
#pragma warning restore 612, 618
        }
    }
}
